packages:
  - 'packages/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!packages/codegen/tests/move/**'
  - '!packages/create-dapp/templates'
  - '!packages/sui/scripts'
  - '!packages/sui/transactions'
  - '!packages/sui/cryptography'
  - '!packages/sui/faucet'
  - '!packages/sui/client'
  - '!packages/sui/verify'
  - '!packages/sui/multisig'
  - '!packages/sui/utils'
  - '!packages/sui/bcs'
  - '!packages/enoki/react'
  - '!packages/sui/graphql'
  - '!packages/sui/keypairs/ed25519'
  - '!packages/sui/keypairs/secp256k1'
  - '!packages/sui/keypairs/secp256r1'
  - '!packages/sui/graphql/schemas/2024.1'
  - '!packages/sui/graphql/schemas/2024.4'
  - '!packages/signers/aws'
  - '!packages/signers/gcp'
  - '!packages/signers/ledger'
  - '!packages/sui/zklogin'
  - '!packages/sui/keypairs/passkey'
  - '!packages/sui/graphql/schemas/latest'
  - '!packages/signers/utils'
  - '!packages/signers/webcrypto'
  - '!packages/zksend/experimental/unified-adapter'
  - '!packages/sui/experimental'
  - '!packages/dapp-kit-next/packages/dapp-kit-core/web'
