// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable no-restricted-globals */

import { existsSync, readdirSync, statSync, writeFileSync } from 'fs';
import { readFile } from 'fs/promises';
import { extname, resolve } from 'path';
import { parseArgs } from 'util';
import { isValidNamedPackage } from '@mysten/sui/utils';
import { prompt } from 'enquirer';
import beautify from 'js-beautify';

const TYPES_AND_TARGET_MATCHES = /[@a-zA-Z0-9/.-]+::[a-zA-Z0-9]+::[a-zA-Z0-9]+/g;
const MVR_NAME_MATCHES = /[@a-zA-Z0-9/.-]+::/g;

const ACCEPTED_FILES = ['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs'];

// TODO: Is there a better way to do this? Maybe through .gitignore? Kinda risky.
const SKIPPED_DIRS = [
	'node_modules',
	'dist',
	'build',
	'target',
	'target-template',
	'.next',
	'out',
	'.pnpm',
	'.yarn',
	'.turbo',
	'.nuxt',
	'.firebase',
	'storybook-static',
	'.docusaurus',
	'.vercel',
	'.bun',
];

const SKIPPED_FILES = ['mvr.ts'];
const MAX_BATCH_SIZE = 25; // files to process per batch.

const BASE_API_URL = (network: 'mainnet' | 'testnet') => `https://qa.${network}.mvr.mystenlabs.com`;

const WARNING_MESSAGE = `/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your "NamedPackagesPlugin" by calling
 * \`getMvrCache("mainnet")\` or \`getMvrCache("testnet")\`
 */
`;

const FILE_NAME = `mvr.ts`;

const { values: args } = parseArgs({
	options: {
		directory: {
			type: 'string',
			default: '.',
			short: 'd',
		},
		fileName: {
			type: 'string',
			default: FILE_NAME,
			short: 'f',
		},
	},
});

async function main() {
	const outDir = resolve(process.cwd(), args.fileName);

	if (existsSync(outDir)) {
		const shouldOverwrite = await prompt({
			type: 'confirm',
			name: 'overwrite',
			message: `The file ${outDir} already exists. Do you want to overwrite it?`,
		});

		if (!shouldOverwrite) {
			return process.exit(0);
		}
	}

	console.log(`Generating ${args.fileName}...`);

	const detectedNames = await findDetectedNamesInFiles(args.directory);

	const mainnetPackages = await resolvePackages(
		Array.from(detectedNames).filter((x) => !x.includes('::')),
		'mainnet',
	);

	const mainnetTypes = await resolveTypes(
		Array.from(detectedNames).filter((x) => x.includes('::')),
		'mainnet',
	);

	const testnetPackages = await resolvePackages(
		Array.from(detectedNames).filter((x) => !x.includes('::')),
		'testnet',
	);

	const testnetTypes = await resolveTypes(
		Array.from(detectedNames).filter((x) => x.includes('::')),
		'testnet',
	);

	const outputFile = `${WARNING_MESSAGE}
const testnetResolution = {
	packages: ${JSON.stringify(testnetPackages).replaceAll('"', "'")},
	types: ${JSON.stringify(testnetTypes).replaceAll('"', "'")},
};

const mainnetResolution = {
	packages: ${JSON.stringify(mainnetPackages).replaceAll('"', "'")},
	types: ${JSON.stringify(mainnetTypes).replaceAll('"', "'")},
};

export function getMvrCache(network: 'mainnet' | 'testnet') {
	return network === 'mainnet' ? mainnetResolution : testnetResolution;
}\n
`;

	writeFileSync(outDir, beautify(outputFile, { indent_size: 4, indent_char: '\t' }), 'utf8');
}

main();

async function resolvePackages(packages: string[], network: 'mainnet' | 'testnet') {
	const batches = batch(packages, 50);

	const results: Record<string, string> = {};

	await Promise.all(
		batches.map(async (batch) => {
			const response = await fetch(`${BASE_API_URL(network)}/v1/resolution/bulk`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					names: batch,
				}),
			});

			const data = await response.json();

			if (!response.ok) throw new Error(`Failed to resolve packages: ${data?.message}`);
			if (!data?.resolution) return;

			for (const pkg of Object.keys(data?.resolution)) {
				const pkgData = data.resolution[pkg]?.package_id;

				if (!pkgData) continue;

				results[pkg] = pkgData;
			}
		}),
	);

	return results;
}

async function resolveTypes(types: string[], network: 'mainnet' | 'testnet') {
	const batches = batch(types, 50);

	const results: Record<string, string> = {};

	await Promise.all(
		batches.map(async (batch) => {
			const response = await fetch(`${BASE_API_URL(network)}/v1/type-resolution/bulk`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					types: batch,
				}),
			});

			const data = await response.json();

			// TODO: Bring this back in once I fix the API.
			// if (!response.ok) throw new Error(`Failed to resolve types: ${data?.message}`);

			if (!data?.resolution) return;

			for (const type of Object.keys(data?.resolution)) {
				const typeData = data.resolution[type]?.type_tag;
				if (!typeData) continue;

				results[type] = typeData;
			}
		}),
	);

	return results;
}

export async function findDetectedNamesInFiles(directory: string) {
	const detectedNames = new Set<string>();
	const files = readFilesRecursively(directory);

	const batches = batch(files);

	for (const batch of batches) {
		await findMvrNamesInFiles(batch, detectedNames);
	}

	return detectedNames;
}

async function findMvrNamesInFiles(files: string[], detectedNames: Set<string>) {
	await Promise.all(
		files.map(async (file) => {
			const content = await readFile(file, 'utf8');
			extractMvrNames(content).forEach((name) => detectedNames.add(name));
		}),
	);
}

function extractMvrNames(content: string) {
	const relevantNames = new Set<string>();
	// find all "fully qualified" matches.
	const fullQualifiedMatches = [...content.matchAll(TYPES_AND_TARGET_MATCHES)];
	fullQualifiedMatches.forEach((match) => {
		const [pkg] = match[0].split('::');

		if (!isValidNamedPackage(pkg)) return;

		relevantNames.add(match[0]);
	});

	// find all "plain" name matches
	const plainNameMatches = [...content.matchAll(MVR_NAME_MATCHES)];
	plainNameMatches.forEach((match) => {
		const [pkg] = match[0].split('::');
		if (!isValidNamedPackage(pkg)) return;

		relevantNames.add(pkg);
	});

	return relevantNames;
}

function readFilesRecursively(dir: string, fileList: string[] = [], currentDepth = 0) {
	const files = readdirSync(dir);

	files.forEach((file) => {
		const filePath = resolve(dir, file);
		const stat = statSync(filePath);

		if (stat.isDirectory()) {
			if (SKIPPED_DIRS.includes(file)) {
				return;
			}

			readFilesRecursively(filePath, fileList, currentDepth + 1);
		} else if (ACCEPTED_FILES.includes(extname(filePath)) && !SKIPPED_FILES.includes(file)) {
			fileList.push(filePath);
		}
	});

	return fileList;
}

function batch<T>(array: T[], batchSize: number = MAX_BATCH_SIZE) {
	const result = [];
	for (let i = 0; i < array.length; i += batchSize) {
		result.push(array.slice(i, i + batchSize)); // Create batches
	}
	return result;
}
