// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
import { existsSync, readdirSync, statSync, writeFileSync } from 'fs';
import { readFile } from 'fs/promises';
import { extname, resolve } from 'path';
import { parseArgs } from 'util';
import type { NamedPackagesPluginCache } from '@mysten/sui/src/transactions';
import { isValidNamedPackage } from '@mysten/sui/utils';
import { prompt } from 'enquirer';
import beautify from 'js-beautify';

const TYPES_AND_TARGET_MATCHES = /[@a-zA-Z0-9/.-]+::[a-zA-Z0-9_]+::[a-zA-Z0-9_]+/g;
const MVR_NAME_MATCHES = /[@a-zA-Z0-9/.-]+::/g;
const ACCEPTED_FILES = ['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs'];

// TODO: Is there a better way to do this? Maybe through .gitignore? Or?
const SKIPPED_DIRS = [
	'node_modules',
	'dist',
	'build',
	'target',
	'target-template',
	'.next',
	'out',
	'.pnpm',
	'.yarn',
	'.turbo',
	'.nuxt',
	'.firebase',
	'storybook-static',
	'.docusaurus',
	'.vercel',
	'.bun',
];

const SKIPPED_FILES = ['mvr.ts'];
const MAX_BATCH_SIZE = 25; // files to process per batch.
const BASE_API_URL = (network: 'mainnet' | 'testnet') => `https://qa.${network}.mvr.mystenlabs.com`;

const WARNING_MESSAGE = `/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your "NamedPackagesPlugin" by calling
 * \`getMvrCache("mainnet")\` or \`getMvrCache("testnet")\`
 */
`;

const FILE_NAME = `mvr.ts`;

const { values: args } = parseArgs({
	options: {
		directory: {
			type: 'string',
			default: '.',
			short: 'd',
		},
		fileName: {
			type: 'string',
			default: FILE_NAME,
			short: 'f',
		},
		depth: {
			type: 'string',
			default: '10',
			short: 'd',
		},
		mainnetUrl: {
			type: 'string',
			default: BASE_API_URL('mainnet'),
		},
		testnetUrl: {
			type: 'string',
			default: BASE_API_URL('testnet'),
		},
	},
});

export async function parser() {
	const outDir = resolve(process.cwd(), args.fileName);

	if (existsSync(outDir)) {
		const shouldOverwrite = await prompt({
			type: 'confirm',
			name: 'overwrite',
			message: `The file ${outDir} already exists. Do you want to overwrite it?`,
		});

		if (!shouldOverwrite) return process.exit(0);
	}

	console.log(`Generating ${args.fileName}...`);

	const detectedNames = await findNames(args.directory, Number(args.depth));

	const { mainnet, testnet } = await crossNetworkResolution(detectedNames);

	writeOutputFile(outDir, mainnet, testnet);
}

function writeOutputFile(
	outDir: string,
	mainnet: NamedPackagesPluginCache,
	testnet: NamedPackagesPluginCache,
) {
	const outputFile = `${WARNING_MESSAGE}
const testnetResolution = {
	packages: ${JSON.stringify(testnet.packages).replaceAll('"', "'")},
	types: ${JSON.stringify(testnet.types).replaceAll('"', "'")},
};

const mainnetResolution = {
	packages: ${JSON.stringify(mainnet.packages).replaceAll('"', "'")},
	types: ${JSON.stringify(mainnet.types).replaceAll('"', "'")},
};

export function getMvrCache(network: 'mainnet' | 'testnet') {
	return network === 'mainnet' ? mainnetResolution : testnetResolution;
}\n
`;

	writeFileSync(outDir, beautify(outputFile, { indent_size: 4, indent_char: '\t' }), 'utf8');
}

export async function crossNetworkResolution(detectedNames: Set<string>) {
	const packages = Array.from(detectedNames).filter((x) => !x.includes('::'));
	const types = Array.from(detectedNames).filter((x) => x.includes('::'));

	const [mainnetPackages, mainnetTypes, testnetPackages, testnetTypes] = await Promise.all([
		resolvePackages(packages, args.mainnetUrl),
		resolveTypes(types, args.mainnetUrl),
		resolvePackages(packages, args.testnetUrl),
		resolveTypes(types, args.testnetUrl),
	]);

	return {
		mainnet: {
			packages: mainnetPackages,
			types: mainnetTypes,
		},
		testnet: {
			packages: testnetPackages,
			types: testnetTypes,
		},
	};
}

async function resolvePackages(packages: string[], apiUrl: string) {
	const batches = batch(packages, 50);

	const results: Record<string, string> = {};

	await Promise.all(
		batches.map(async (batch) => {
			const response = await fetch(`${apiUrl}/v1/resolution/bulk`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					names: batch,
				}),
			});

			const data = await response.json();

			if (!response.ok) throw new Error(`Failed to resolve packages: ${data?.message}`);
			if (!data?.resolution) return;

			for (const pkg of Object.keys(data?.resolution)) {
				const pkgData = data.resolution[pkg]?.package_id;

				if (!pkgData) continue;

				results[pkg] = pkgData;
			}
		}),
	);

	return results;
}

// TODO: Switch to `/struct-definition/bulk` endpoint when released,
// as this endpoint will be the right one for "non-nested" struct resolution.
// The current endpoint will fail with "generic" parameter lookups (which are not existent)
// on this parser.
async function resolveTypes(types: string[], apiUrl: string) {
	const batches = batch(types, 50);

	const results: Record<string, string> = {};

	await Promise.all(
		batches.map(async (batch) => {
			const response = await fetch(`${apiUrl}/v1/type-resolution/bulk`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					types: batch,
				}),
			});

			const data = await response.json();

			if (!response.ok) throw new Error(`Failed to resolve types: ${data?.message}`);

			if (!data?.resolution) return;

			for (const type of Object.keys(data?.resolution)) {
				const typeData = data.resolution[type]?.type_tag;
				if (!typeData) continue;

				results[type] = typeData;
			}
		}),
	);

	return results;
}

/**
 * Finds all the MVR names in the given directory.
 * @param directory - The directory to search for MVR names.
 * @returns A set of all the MVR names found in the directory.
 */
export async function findNames(directory: string, depth: number = 10) {
	const detectedNames = new Set<string>();
	const files = readFilesRecursively(directory, depth);

	// We batch the files to avoid trying to open too many files at once.
	const batches = batch(files);

	for (const batch of batches) {
		await processFilesBatch(batch, detectedNames);
	}

	return detectedNames;
}

/**
 * Finds all the MVR names in the given files.
 */
async function processFilesBatch(files: string[], detectedNames: Set<string>) {
	await Promise.all(
		files.map(async (file) => {
			const content = await readFile(file, 'utf8');
			extractMvrNames(content).forEach((name) => detectedNames.add(name));
		}),
	);
}

/**
 * Extracts all the MVR names from the given file's data (content).
 */
function extractMvrNames(content: string) {
	const relevantNames = new Set<string>();
	// find all "fully qualified" matches.
	const fullQualifiedMatches = [...content.matchAll(TYPES_AND_TARGET_MATCHES)];
	fullQualifiedMatches.forEach((match) => {
		const [pkg] = match[0].split('::');

		if (!isValidNamedPackage(pkg)) return;

		relevantNames.add(match[0]);
	});

	// find all "plain" name matches
	const plainNameMatches = [...content.matchAll(MVR_NAME_MATCHES)];
	plainNameMatches.forEach((match) => {
		const [pkg] = match[0].split('::');
		if (!isValidNamedPackage(pkg)) return;

		relevantNames.add(pkg);
	});

	return relevantNames;
}

/**
 * Find all the matching files in the given directory,
 * and recursively search for files in subdirectories.
 */
function readFilesRecursively(
	dir: string,
	maxDepth: number = 10,
	fileList: string[] = [],
	currentDepth = 0,
) {
	// We limit the depth to avoid going too deep into the directory tree.
	if (currentDepth > maxDepth) return fileList;

	const files = readdirSync(dir);

	files.forEach((file) => {
		const filePath = resolve(dir, file);
		const stat = statSync(filePath);

		if (stat.isDirectory()) {
			if (SKIPPED_DIRS.includes(file)) {
				return;
			}

			readFilesRecursively(filePath, maxDepth, fileList, currentDepth + 1);
		} else if (ACCEPTED_FILES.includes(extname(filePath)) && !SKIPPED_FILES.includes(file)) {
			fileList.push(filePath);
		}
	});

	return fileList;
}

/**
 * Batch the given array into smaller arrays of the given size.
 */
function batch<T>(array: T[], batchSize: number = MAX_BATCH_SIZE) {
	const result = [];
	for (let i = 0; i < array.length; i += batchSize) {
		result.push(array.slice(i, i + batchSize)); // Create batches
	}
	return result;
}
