// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Regenerates `src/deployments/<network>.ts` from a deployment manifest in the sibling
 * `deepbookv3` checkout.
 *
 * The manifest is the record the deploy tooling writes, so it is the only place these ids
 * are authored. Transcribing them by hand into the SDK is what lets a redeploy leave one
 * subpath addressing a retired package while its siblings move on — the reason this script
 * exists rather than a hand-maintained constants file.
 *
 * Check the sibling checkout out to the deploy anchor first, exactly as `pnpm codegen`
 * requires:
 *
 *   pnpm --filter @mysten/deepbook-v3 sync-deployment
 *   pnpm --filter @mysten/deepbook-v3 sync-deployment -- --manifest /path/to/deployment.testnet.json
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const DEFAULT_MANIFEST = '../../../deepbookv3/packages/predict/deployment/deployment.testnet.json';
const SUPPORTED_SCHEMA = 6;

interface Manifest {
	schemaVersion: number;
	deployment: string;
	network: string;
	chainId: string;
	sourceCommit: string;
	packages: Record<string, string>;
	coinTypes: Record<string, string>;
	objects: Record<string, string>;
	underlyings: Record<string, Record<string, unknown>>;
}

function arg(name: string): string | undefined {
	const i = process.argv.indexOf(`--${name}`);
	return i === -1 ? undefined : process.argv[i + 1];
}

function req(obj: Record<string, string>, key: string, where: string): string {
	const v = obj?.[key];
	if (typeof v !== 'string' || !v) {
		throw new Error(`manifest is missing ${where}.${key} — cannot generate a partial record`);
	}
	return v;
}

const manifestPath = resolve(process.cwd(), arg('manifest') ?? DEFAULT_MANIFEST);
let manifest: Manifest;
try {
	manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
} catch (cause) {
	throw new Error(
		`could not read the deployment manifest at ${manifestPath}. ` +
			'Check the sibling deepbookv3 checkout out to the deploy anchor, or pass --manifest.',
		{ cause },
	);
}

// A schema bump can move or re-key ids. Failing here beats emitting a file whose ids are
// silently `undefined`.
if (manifest.schemaVersion !== SUPPORTED_SCHEMA) {
	throw new Error(
		`manifest schemaVersion ${manifest.schemaVersion} is not supported (expected ${SUPPORTED_SCHEMA}). ` +
			'Re-read the manifest and update this script before regenerating.',
	);
}

const { packages: p, objects: o, coinTypes: c } = manifest;

const underlyings = Object.entries(manifest.underlyings ?? {})
	.map(
		([symbol, u]) => `		${symbol}: {
			symbol: '${u.symbol}',
			propbookUnderlyingId: ${u.propbookUnderlyingId},
			pythFeed: '${u.pythFeed}',
			blockScholesValueStore: '${u.blockScholesValueStore}',
			blockScholesSviStore: '${u.blockScholesSviStore}',
		},`,
	)
	.join('\n');

const out = `// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by \`pnpm sync-deployment\` from the deploy tooling's own manifest
// (\`packages/predict/deployment/deployment.${manifest.network}.json\`). Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: ${manifest.deployment}
// sourceCommit: ${manifest.sourceCommit}
//
// Deliberately dependency-free — every subpath reads a slice of this, so an import here
// would pull that module into all of their graphs.

/** Which on-chain deployment the ids below came from. */
export const ${manifest.network.toUpperCase()}_DEPLOYMENT = {
	deployment: '${manifest.deployment}',
	network: '${manifest.network}',
	chainId: '${manifest.chainId}',
	sourceCommit: '${manifest.sourceCommit}',
} as const;

/** Ids for the shared \`account\` primitive — the \`/account\` subpath's slice. */
export const ${manifest.network.toUpperCase()}_ACCOUNT = {
	accountPackageId: '${req(p, 'account', 'packages')}',
	accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
} as const;

/**
 * Ids for time-limited sessions — the \`/sessions\` subpath's slice.
 *
 * \`deepbookRegistry\` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const ${manifest.network.toUpperCase()}_SESSIONS = {
	sessionsPackageId: '${req(p, 'sessions', 'packages')}',
	sessionsConfig: '${req(o, 'sessionsConfig', 'objects')}',
	accountPackageId: '${req(p, 'account', 'packages')}',
	accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
	deepbookRegistry: '${req(o, 'deepbookRegistry', 'objects')}',
	deepbookCoreAccountPackageId: '${req(p, 'deepbookCoreAccount', 'packages')}',
} as const;

/** Ids for DeepBook Predict — the \`/predict\` subpath's slice. */
export const ${manifest.network.toUpperCase()}_PREDICT = {
	network: '${manifest.network}',
	packages: {
		predict: '${req(p, 'predict', 'packages')}',
		account: '${req(p, 'account', 'packages')}',
		propbook: '${req(p, 'propbook', 'packages')}',
	},
	objects: {
		registry: '${req(o, 'registry', 'objects')}',
		protocolConfig: '${req(o, 'protocolConfig', 'objects')}',
		poolVault: '${req(o, 'poolVault', 'objects')}',
		oracleRegistry: '${req(o, 'oracleRegistry', 'objects')}',
		accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
	},
	quoteCoinType: '${req(c, 'dusdc', 'coinTypes')}',
	underlyings: {
${underlyings}
	},
} as const;
`;

const target = resolve(process.cwd(), `src/deployments/${manifest.network}.ts`);
writeFileSync(target, out);
console.log(`wrote ${target} from ${manifest.deployment} (sourceCommit ${manifest.sourceCommit})`);
