// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Regenerates `src/deployments/<network>.ts` from a deployment manifest in the sibling
 * `deepbookv3` checkout.
 *
 * The manifest is the record the deploy tooling writes, so it is the only place these ids
 * are authored. Transcribing them by hand into the SDK is what lets a redeploy leave one
 * subpath addressing a retired package while its siblings move on — the reason this script
 * exists rather than a hand-maintained constants file.
 *
 * Check the sibling checkout out to the DEPLOYMENT BRANCH — not the manifest's own
 * `sourceCommit`. The deploy tooling writes the manifest in a commit that lands *after* the
 * sources it deployed, so the manifest does not exist at `sourceCommit`. For
 * `predict-testnet-8-21` that trailing commit adds only `Published.toml` files and the
 * manifest itself, no Move sources — so the branch tip is also the right ref for
 * `pnpm codegen`, and one checkout serves both.
 *
 * The npm script chains `prettier --write` over the output, the way `codegen` chains
 * `lint:fix` — the emitted file is not formatted, so without it a fresh regeneration leaves
 * the repo failing `prettier:check`.
 *
 *   git -C ../../../deepbookv3 checkout predict-testnet-8-21
 *   pnpm --filter @mysten/deepbook-v3 sync-deployment
 *   pnpm --filter @mysten/deepbook-v3 sync-deployment -- --manifest /path/to/deployment.testnet.json
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const DEFAULT_MANIFEST = '../../../deepbookv3/packages/predict/deployment/deployment.testnet.json';
const SUPPORTED_SCHEMA = 6;

interface Manifest {
	schemaVersion: number;
	deployment: string;
	network: string;
	chainId: string;
	sourceCommit: string;
	packages: Record<string, string>;
	coinTypes: Record<string, string>;
	objects: Record<string, string>;
	underlyings: Record<string, Record<string, unknown>>;
	initialConfiguration: { units: Record<string, number> };
}

function arg(name: string): string | undefined {
	const i = process.argv.indexOf(`--${name}`);
	return i === -1 ? undefined : process.argv[i + 1];
}

function req(obj: Record<string, string>, key: string, where: string): string {
	const v = obj?.[key];
	if (typeof v !== 'string' || !v) {
		throw new Error(`manifest is missing ${where}.${key} — cannot generate a partial record`);
	}
	return v;
}

const manifestPath = resolve(process.cwd(), arg('manifest') ?? DEFAULT_MANIFEST);
let manifest: Manifest;
try {
	manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
} catch (cause) {
	throw new Error(
		`could not read the deployment manifest at ${manifestPath}. ` +
			'Check the sibling deepbookv3 checkout out to the deployment BRANCH (e.g. ' +
			"`predict-testnet-8-21`), not to the manifest's sourceCommit — the deploy tooling " +
			'writes the manifest in a later commit, so it does not exist at that commit. ' +
			'Or pass --manifest with an explicit path.',
		{ cause },
	);
}

// A schema bump can move or re-key ids. Failing here beats emitting a file whose ids are
// silently `undefined`.
if (manifest.schemaVersion !== SUPPORTED_SCHEMA) {
	throw new Error(
		`manifest schemaVersion ${manifest.schemaVersion} is not supported (expected ${SUPPORTED_SCHEMA}). ` +
			'Re-read the manifest and update this script before regenerating.',
	);
}

const { packages: p, objects: o, coinTypes: c } = manifest;

// Validated the same way as everything else. Interpolating these raw is how a renamed or
// missing manifest key becomes the literal string 'undefined' in a shipped id — which
// compiles, passes every test, and only surfaces as "Object undefined not found" at
// simulate time.
const underlyings = Object.entries(manifest.underlyings ?? {})
	.map(([symbol, u]) => {
		const where = `underlyings.${symbol}`;
		const num = (key: string): number => {
			const v = u?.[key];
			if (typeof v !== 'number' || !Number.isFinite(v)) {
				throw new Error(`manifest is missing a numeric ${where}.${key}`);
			}
			return v;
		};
		return `		${symbol}: {
			symbol: '${req(u as Record<string, string>, 'symbol', where)}',
			propbookUnderlyingId: ${num('propbookUnderlyingId')},
			pythFeed: '${req(u as Record<string, string>, 'pythFeed', where)}',
			blockScholesValueStore: '${req(u as Record<string, string>, 'blockScholesValueStore', where)}',
			blockScholesSviStore: '${req(u as Record<string, string>, 'blockScholesSviStore', where)}',
		},`;
	})
	.join('\n');

const out = `// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by \`pnpm sync-deployment\` from the deploy tooling's own manifest
// (\`packages/predict/deployment/deployment.${manifest.network}.json\`). Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: ${manifest.deployment}
// sourceCommit: ${manifest.sourceCommit}
//
// Deliberately dependency-free — every subpath reads a slice of this, so an import here
// would pull that module into all of their graphs.

/** Which on-chain deployment the ids below came from. */
export const ${manifest.network.toUpperCase()}_DEPLOYMENT = {
	deployment: '${manifest.deployment}',
	network: '${manifest.network}',
	chainId: '${manifest.chainId}',
	sourceCommit: '${manifest.sourceCommit}',
} as const;

/** Ids for the shared \`account\` primitive — the \`/account\` subpath's slice. */
export const ${manifest.network.toUpperCase()}_ACCOUNT = {
	accountPackageId: '${req(p, 'account', 'packages')}',
	accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
} as const;

/**
 * Ids for time-limited sessions — the \`/sessions\` subpath's slice.
 *
 * \`deepbookRegistry\` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const ${manifest.network.toUpperCase()}_SESSIONS = {
	sessionsPackageId: '${req(p, 'sessions', 'packages')}',
	sessionsConfig: '${req(o, 'sessionsConfig', 'objects')}',
	accountPackageId: '${req(p, 'account', 'packages')}',
	accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
	deepbookRegistry: '${req(o, 'deepbookRegistry', 'objects')}',
	deepbookCoreAccountPackageId: '${req(p, 'deepbookCoreAccount', 'packages')}',
	/** Required by every Predict session wrapper — they all take \`config: &ProtocolConfig\`. */
	protocolConfig: '${req(o, 'protocolConfig', 'objects')}',
} as const;

/** Ids for DeepBook Predict — the \`/predict\` subpath's slice. */
export const ${manifest.network.toUpperCase()}_PREDICT = {
	network: '${manifest.network}',
	packages: {
		predict: '${req(p, 'predict', 'packages')}',
		account: '${req(p, 'account', 'packages')}',
		propbook: '${req(p, 'propbook', 'packages')}',
	},
	objects: {
		registry: '${req(o, 'registry', 'objects')}',
		protocolConfig: '${req(o, 'protocolConfig', 'objects')}',
		poolVault: '${req(o, 'poolVault', 'objects')}',
		oracleRegistry: '${req(o, 'oracleRegistry', 'objects')}',
		accountRegistry: '${req(o, 'accountRegistry', 'objects')}',
	},
	quoteCoinType: '${req(c, 'dusdc', 'coinTypes')}',
	/**
	 * \`plp\` is the LP share coin type. It is NOT derivable from \`packages.predict\`: a Move
	 * type tag keeps the ORIGINAL package id across an upgrade, while \`packages.predict\`
	 * moves to the latest. They agree only while predict is at v1.
	 */
	coinTypes: {
		plp: '${req(c, 'plp', 'coinTypes')}',
		deep: '${req(c, 'deep', 'coinTypes')}',
	},
	/** Scale constants the deploy owns; the SDK otherwise hardcodes these. */
	units: {
		positionLotSize: ${manifest.initialConfiguration.units.positionLotSize},
		fixedPointScale: ${manifest.initialConfiguration.units.fixedPointScale},
		quoteCoinDecimals: ${manifest.initialConfiguration.units.quoteCoinDecimals},
		positionQuantityDecimals: ${manifest.initialConfiguration.units.positionQuantityDecimals},
	},
	underlyings: {
${underlyings}
	},
} as const;
`;

const target = resolve(process.cwd(), `src/deployments/${manifest.network}.ts`);
writeFileSync(target, out);
console.log(`wrote ${target} from ${manifest.deployment} (sourceCommit ${manifest.sourceCommit})`);
