// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs';
import path from 'node:path';

import { source } from '@/lib/source';
import type { InferPageType } from 'fumadocs-core/source';

export const revalidate = false;

export async function GET(request: Request, props: { params: Promise<{ path?: string[] }> }) {
	const params = await props.params;
	const pathSegments = params.path ?? [];

	// Root /llms.txt — serve structured index
	if (pathSegments.length === 0) {
		const url = new URL(request.url);
		const baseUrl = `${url.protocol}//${url.host}`;
		return buildIndex(baseUrl);
	}

	// /llms.txt/:path — serve section content
	const folderPath = '/' + pathSegments.join('/');

	const pages = source
		.getPages()
		.filter((page) => page.url === folderPath || page.url.startsWith(folderPath + '/'))
		.sort((a, b) => {
			if (a.url === folderPath) return -1;
			if (b.url === folderPath) return 1;
			return a.url.localeCompare(b.url);
		});

	if (pages.length === 0) {
		return new Response('Not found', { status: 404 });
	}

	const texts = await Promise.all(pages.map(getLLMText));
	return new Response(texts.join('\n\n---\n\n'), {
		headers: {
			'Content-Type': 'text/plain; charset=utf-8',
			'Cache-Control': 'public, max-age=0, must-revalidate',
		},
	});
}

function buildIndex(baseUrl: string) {
	// Try to read the pre-built index generated by build-docs.ts / generate-llms-index.ts
	const distIndex = path.resolve(process.cwd(), 'dist', 'llms-index.md');
	if (fs.existsSync(distIndex)) {
		let content = fs.readFileSync(distIndex, 'utf-8');
		// Rewrite relative links (./section/page.md) to absolute URLs
		content = content.replace(/\(\.\/([^)]+\.md)\)/g, `(${baseUrl}/$1)`);
		return new Response(content, {
			headers: {
				'Content-Type': 'text/plain; charset=utf-8',
				'Cache-Control': 'public, max-age=0, must-revalidate',
			},
		});
	}

	// Fallback: build from fumadocs source with hierarchy from page URLs
	const pages = source.getPages().sort((a, b) => a.url.localeCompare(b.url));

	const lines: string[] = [];
	lines.push('# Sui TypeScript SDK Documentation');
	lines.push('');
	lines.push(
		'> Reference documentation for the @mysten/* TypeScript SDK packages for the Sui blockchain.',
	);
	lines.push('');

	// Group pages by top-level section, preserving subsection nesting
	let currentSection = '';
	let currentSubsection = '';

	for (const page of pages) {
		const parts = page.url.replace(/^\//, '').split('/');
		const section = parts[0] || 'General';
		const subsection = parts.length >= 3 ? parts.slice(0, 2).join('/') : null;

		if (section !== currentSection) {
			currentSection = section;
			currentSubsection = '';
			lines.push(`## ${section}`);
			lines.push('');
		}

		if (subsection && subsection !== currentSubsection) {
			currentSubsection = subsection;
			lines.push(`### ${parts[1]}`);
			lines.push('');
		}

		const indent = parts.length > 2 ? '  ' : '';
		const desc = page.data.description ? `: ${page.data.description}` : '';
		lines.push(`${indent}- [${page.data.title}](${baseUrl}${page.url}.md)${desc}`);
	}

	lines.push('');

	return new Response(lines.join('\n'), {
		headers: {
			'Content-Type': 'text/plain; charset=utf-8',
			'Cache-Control': 'public, max-age=0, must-revalidate',
		},
	});
}

async function getLLMText(page: InferPageType<typeof source>) {
	const processed = await page.data.getText?.('processed');
	return `# ${page.data.title} (${page.url})\n\n${processed ?? ''}`;
}
