// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

import * as fs from 'node:fs';
import * as path from 'node:path';

const packageRoot = path.resolve(import.meta.url.slice(5), '../..');
const outputFile = path.join(packageRoot, 'src/grpc/proto/types.ts');

// Directories whose generated types should be re-exported from `GrpcTypes`.
const protoDirs = ['sui/rpc/v2', 'sui/forking/v1alpha'];

const exports: string[] = [];
let total = 0;
for (const relDir of protoDirs) {
	const absDir = path.join(packageRoot, 'src/grpc/proto', relDir);
	const files = fs
		.readdirSync(absDir)
		.filter((file) => file.endsWith('.ts') && !file.endsWith('.client.ts'))
		.sort();
	for (const file of files) {
		const moduleName = file.replace('.ts', '.js');
		exports.push(`export * from './${relDir}/${moduleName}';`);
	}
	total += files.length;
}

const header = `// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is auto-generated by scripts/generate-grpc-types.ts
 * Run \`pnpm codegen:grpc\` to regenerate.
 */

// Re-export all gRPC proto types for easy consumption
`;

const content = header + exports.join('\n') + '\n';

fs.writeFileSync(outputFile, content);

console.log(`Generated ${outputFile} with ${total} exports`);
