// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

import { readFile, writeFile } from 'fs/promises';

const LICENSE = '// Copyright (c) Mysten Labs, Inc.\n// SPDX-License-Identifier: Apache-2.0\n\n';

const WARNING = '// This file is generated by genversion.mjs. Do not edit it directly.\n\n';

// Pulls `version = "..."` from the [workspace.package] table without a TOML
// dep. Tradeoff: keeps the release-time install minimal — full TOML parsing is
// overkill for a single string field in a stable upstream layout.
function extractWorkspacePackageVersion(cargoToml) {
	const sectionRe = /^\[workspace\.package\]\s*$([\s\S]*?)(?=^\s*\[|\z)/m;
	const section = cargoToml.match(sectionRe);
	if (!section) {
		throw new Error('genversion: [workspace.package] section not found in Cargo.toml');
	}
	const versionRe = /^\s*version\s*=\s*"([^"]+)"/m;
	const version = section[1].match(versionRe);
	if (!version) {
		throw new Error('genversion: version field not found in [workspace.package]');
	}
	return version[1];
}

async function main() {
	const pkg = JSON.parse(await readFile('./package.json', 'utf8'));
	const cargoToml = await fetch(
		'https://raw.githubusercontent.com/MystenLabs/sui/refs/heads/main/Cargo.toml',
	).then((res) => res.text());
	const targetedRpcVersion = extractWorkspacePackageVersion(cargoToml);
	await writeFile(
		'src/version.ts',
		LICENSE +
			WARNING +
			`export const PACKAGE_VERSION = '${pkg.version}';\nexport const TARGETED_RPC_VERSION = '${targetedRpcVersion}';\n`,
	);
}

await main();
