// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// This file is generated by genversion.mjs. Do not edit it directly.

<<<<<<< HEAD
export const PACKAGE_VERSION = '1.38.0';
=======
export const PACKAGE_VERSION = '1.37.6';
>>>>>>> 8f034081 ([core-client] update schemas and add getMoveFunction method)
export const TARGETED_RPC_VERSION = '1.58.0';
