// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by `pnpm sync-deployment` from the deploy tooling's own manifest
// (`packages/predict/deployment/deployment.mainnet.json`) and the Predict/Sessions
// `Published.toml` records for current call targets and original type IDs. Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: deepbook-predict-mainnet
// sourceCommit: 7b169bde2c2a25fee3ac9aa4686e346309bfe570
//
// Runtime-dependency-free — every subpath reads a slice of this, so a value import here
// would pull that module into all of their graphs. The type import below is erased.
//
// Frozen: these are shared module singletons, so an accessor handing one to a caller who
// mutates it would change what every other caller sees.

import type {
	AccountIds,
	DeploymentInfo,
	DeploymentUnits,
	PredictIds,
	SessionsIds,
} from './types.js';

/** Which on-chain deployment the ids below came from. */
export const MAINNET_DEPLOYMENT: DeploymentInfo = Object.freeze({
	deployment: 'deepbook-predict-mainnet',
	network: 'mainnet',
	chainId: '35834a8a',
	sourceCommit: '7b169bde2c2a25fee3ac9aa4686e346309bfe570',
});

/** Ids for the shared `account` primitive — the `/account` subpath's slice. */
export const MAINNET_ACCOUNT: AccountIds = Object.freeze({
	accountPackageId: '0x4e1dd01465713c9d832313fed5f45c222a4d5c62a533d6da96764c8b2a245d58',
	accountRegistry: '0x8c52c6f5b2374e33f4a726d9c32337b1aee3a71410d41c18faa91d938d66e4bc',
});

/**
 * Ids for time-limited sessions — the `/sessions` subpath's slice.
 *
 * `deepbookRegistry` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const MAINNET_SESSIONS: SessionsIds = Object.freeze({
	sessionsPackageId: '0xec678aee98cd161bdce62ff3dcf4893574df29d927dc8b573f6b4563ec960a1a',
	sessionsPackageIdV1: '0x9a068beffa019ae756f4a6d2611e9899d3c6dd888812dd9eca87535d2ac55e2a',
	sessionsConfig: '0xb2fba483748aac7508676020d4e691d68239b66f8bf7c5e7634dd1a76a329317',
	accountPackageId: '0x4e1dd01465713c9d832313fed5f45c222a4d5c62a533d6da96764c8b2a245d58',
	accountRegistry: '0x8c52c6f5b2374e33f4a726d9c32337b1aee3a71410d41c18faa91d938d66e4bc',
	deepbookRegistry: '0xaf16199a2dff736e9f07a845f23c5da6df6f756eddb631aed9d24a93efc4549d',
	deepbookCoreAccountPackageId:
		'0xd71b5a341dc8dc7e187517849edf61e54670b60fe496e07186c09a65fa7afdb7',
	/** Required by every Predict session wrapper — they all take `config: &ProtocolConfig`. */
	protocolConfig: '0x5fa6efbe7691809565a660adde23f0c184ca1d19cefafa4e1c88d655fe279580',
});

/**
 * Scale constants the deployment owns rather than the SDK. Deployment-wide:
 * `quoteCoinDecimals` and `fixedPointScale` apply to any subpath formatting a custody
 * balance, not just Predict.
 */
export const MAINNET_UNITS: DeploymentUnits = Object.freeze({
	positionLotSize: 10000,
	fixedPointScale: 1000000000,
	quoteCoinDecimals: 6,
	positionQuantityDecimals: 6,
});

/** Ids for DeepBook Predict — the `/predict` subpath's slice. */
export const MAINNET_PREDICT: PredictIds = Object.freeze({
	network: 'mainnet',
	packages: Object.freeze({
		predict: '0x1cacb9bf963b1b62139d0ad94cc8ce0d9e5792011932df9925ce07aa3c70a837',
		predictV1: '0x89aea622e7bb3bdd598bde87dde40ee31c9eed4971b9546e23ec83de3c48bbba',
		account: '0x4e1dd01465713c9d832313fed5f45c222a4d5c62a533d6da96764c8b2a245d58',
		propbook: '0xa6c8f32015b5b41d34ee09995a2e9d7a21cdecf0e1910a50b264fd252cd33831',
	}),
	objects: Object.freeze({
		registry: '0x94327dbc256a2cfabd164c2bf4b3fe033bfaa4771f7a6f716954e07cb1b4beba',
		protocolConfig: '0x5fa6efbe7691809565a660adde23f0c184ca1d19cefafa4e1c88d655fe279580',
		poolVault: '0x4d227a1baf8cfcaf6e652a9182d0e63f85f9ce82cd542fdf3356bb3581be3b99',
		oracleRegistry: '0x5d62c0d9be43efa769a708ade53fbe5bea98c15c865b64ca7c498c87b045a698',
		accountRegistry: '0x8c52c6f5b2374e33f4a726d9c32337b1aee3a71410d41c18faa91d938d66e4bc',
	}),
	quoteCoinType: '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
	/**
	 * `plp` is the LP share coin type. It is NOT derivable from `packages.predict`: a Move
	 * type tag keeps the ORIGINAL package id across an upgrade, while `packages.predict`
	 * moves to the latest. They agree only while predict is at v1.
	 */
	coinTypes: Object.freeze({
		plp: '0x89aea622e7bb3bdd598bde87dde40ee31c9eed4971b9546e23ec83de3c48bbba::plp::PLP',
		deep: '0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP',
	}),
	units: MAINNET_UNITS,
	underlyings: Object.freeze({
		BTC: Object.freeze({
			symbol: 'BTC',
			propbookUnderlyingId: 1,
			pythFeed: '0x4c5d2b4c8238f04b7687c3a8df915b69c50d5f4d291fc49aea44bdb6b52e1a20',
			blockScholesValueStore: '0xe83f843b15ae63045b2cea445fb8ea7ad85c5fc2a05f66db122a511e1f2c67bc',
			blockScholesSviStore: '0xfdd447be39d847747caf18ecf3355031bb33979c472581f1a5481375d3748bfb',
		}),
	}),
});
