// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by `pnpm sync-deployment` from the deploy tooling's own manifest
// (`packages/predict/deployment/deployment.mainnet.json`). Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: deepbook-predict-mainnet
// sourceCommit: 14a7e8f822e0397df2d61fbfbce3ef21086891c2
//
// Runtime-dependency-free — every subpath reads a slice of this, so a value import here
// would pull that module into all of their graphs. The type import below is erased.
//
// Frozen: these are shared module singletons, so an accessor handing one to a caller who
// mutates it would change what every other caller sees.

import type {
	AccountIds,
	DeploymentInfo,
	DeploymentUnits,
	PredictIds,
	SessionsIds,
} from './types.js';

/** Which on-chain deployment the ids below came from. */
export const MAINNET_DEPLOYMENT: DeploymentInfo = Object.freeze({
	deployment: 'deepbook-predict-mainnet',
	network: 'mainnet',
	chainId: '35834a8a',
	sourceCommit: '14a7e8f822e0397df2d61fbfbce3ef21086891c2',
});

/** Ids for the shared `account` primitive — the `/account` subpath's slice. */
export const MAINNET_ACCOUNT: AccountIds = Object.freeze({
	accountPackageId: '0xa6f1b22aaeb429f6fd8f01c13f605256e00876457fd122da8a0e2c1045c75929',
	accountRegistry: '0x210ba485d973b5356e9078318837137efabdd5ffb9eeb3705ba7eef3340324fc',
});

/**
 * Ids for time-limited sessions — the `/sessions` subpath's slice.
 *
 * `deepbookRegistry` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const MAINNET_SESSIONS: SessionsIds = Object.freeze({
	sessionsPackageId: '0xebfa125baee571c1f8c903c1dd54a5bc57949db82469b836c32eca251756c82a',
	sessionsConfig: '0x0c5f64365b3bf1f67827d6975893190079cc048247f9ff0b08390aa9ee697c5c',
	accountPackageId: '0xa6f1b22aaeb429f6fd8f01c13f605256e00876457fd122da8a0e2c1045c75929',
	accountRegistry: '0x210ba485d973b5356e9078318837137efabdd5ffb9eeb3705ba7eef3340324fc',
	deepbookRegistry: '0xaf16199a2dff736e9f07a845f23c5da6df6f756eddb631aed9d24a93efc4549d',
	deepbookCoreAccountPackageId:
		'0xebcd5b403ee78021e3f78d1c77e2117a676caa8a9754dedb99e7b102b0d81872',
	/** Required by every Predict session wrapper — they all take `config: &ProtocolConfig`. */
	protocolConfig: '0x55e8800bcb31b792683ca4385bd533716e2a9721364236a69ee2c3bee61dd8f2',
});

/**
 * Scale constants the deployment owns rather than the SDK. Deployment-wide:
 * `quoteCoinDecimals` and `fixedPointScale` apply to any subpath formatting a custody
 * balance, not just Predict.
 */
export const MAINNET_UNITS: DeploymentUnits = Object.freeze({
	positionLotSize: 10000,
	fixedPointScale: 1000000000,
	quoteCoinDecimals: 6,
	positionQuantityDecimals: 6,
});

/** Ids for DeepBook Predict — the `/predict` subpath's slice. */
export const MAINNET_PREDICT: PredictIds = Object.freeze({
	network: 'mainnet',
	packages: Object.freeze({
		predict: '0x774f9555865a7b96e31ec982f62d5bdf9d74bf57a6468b5ed41340c231afd7df',
		account: '0xa6f1b22aaeb429f6fd8f01c13f605256e00876457fd122da8a0e2c1045c75929',
		propbook: '0x2a63e378ab0138cdcb12651a093f3799f8b8e4f6c927ce6de0e8bc7ded0ec49d',
	}),
	objects: Object.freeze({
		registry: '0xc98e430d82bed9f777288061faa1988da705a97db7f0da9f215ab372c53a2362',
		protocolConfig: '0x55e8800bcb31b792683ca4385bd533716e2a9721364236a69ee2c3bee61dd8f2',
		poolVault: '0x3f80653bf9324162254d89724276aae7b36ba7c83d4650214afbf266da98f492',
		oracleRegistry: '0x1ff67a8499b0af7c0fbb26ba82c319be25413af93d9a961ee60f8d1229e7de7c',
		accountRegistry: '0x210ba485d973b5356e9078318837137efabdd5ffb9eeb3705ba7eef3340324fc',
	}),
	quoteCoinType: '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
	/**
	 * `plp` is the LP share coin type. It is NOT derivable from `packages.predict`: a Move
	 * type tag keeps the ORIGINAL package id across an upgrade, while `packages.predict`
	 * moves to the latest. They agree only while predict is at v1.
	 */
	coinTypes: Object.freeze({
		plp: '0x774f9555865a7b96e31ec982f62d5bdf9d74bf57a6468b5ed41340c231afd7df::plp::PLP',
		deep: '0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP',
	}),
	units: MAINNET_UNITS,
	underlyings: Object.freeze({
		BTC: Object.freeze({
			symbol: 'BTC',
			propbookUnderlyingId: 1,
			pythFeed: '0x44bd2e00549973bb6a58785836e97ed80b4979e67dc3bf312c997e56053e5376',
			blockScholesValueStore: '0xe7c83ee4ac0c300d68d8d4c3d265d78287b4767dcbc5f279cd6f210b6248d493',
			blockScholesSviStore: '0x8e5568aebf490c2adfd4e010a9b4ddcf7c774183f58c98fcd438bae1fc68f561',
		}),
	}),
});
