// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by `pnpm sync-deployment` from the deploy tooling's own manifest
// (`packages/predict/deployment/deployment.testnet.json`). Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: deepbook-predict-testnet
// sourceCommit: a928bd2da4b71abf7c4ea6f66abec2763308331e
//
// Runtime-dependency-free — every subpath reads a slice of this, so a value import here
// would pull that module into all of their graphs. The type import below is erased.
//
// Frozen: these are shared module singletons, so an accessor handing one to a caller who
// mutates it would change what every other caller sees.

import type {
	AccountIds,
	DeploymentInfo,
	DeploymentUnits,
	PredictIds,
	SessionsIds,
} from './types.js';

/** Which on-chain deployment the ids below came from. */
export const TESTNET_DEPLOYMENT: DeploymentInfo = Object.freeze({
	deployment: 'deepbook-predict-testnet',
	network: 'testnet',
	chainId: '4c78adac',
	sourceCommit: 'a928bd2da4b71abf7c4ea6f66abec2763308331e',
});

/** Ids for the shared `account` primitive — the `/account` subpath's slice. */
export const TESTNET_ACCOUNT: AccountIds = Object.freeze({
	accountPackageId: '0x543139156cb90d1a73df33b5dca37d7c8bdce62506c7874ebc854afd319b98f1',
	accountRegistry: '0xb889caefe327cbdea58e529e3b9e10dc93f1e661ddef32824d28527edf8d6385',
});

/**
 * Ids for time-limited sessions — the `/sessions` subpath's slice.
 *
 * `deepbookRegistry` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const TESTNET_SESSIONS: SessionsIds = Object.freeze({
	sessionsPackageId: '0x10c91d168dc4a04357f9d23795a204092ca46e5b97f8b9ef26fea95664d5bb38',
	sessionsConfig: '0x63cde7c7d846f15c51802ec3d44ba44918658e3155b0d2e0cb26d6fc1b4dadd8',
	accountPackageId: '0x543139156cb90d1a73df33b5dca37d7c8bdce62506c7874ebc854afd319b98f1',
	accountRegistry: '0xb889caefe327cbdea58e529e3b9e10dc93f1e661ddef32824d28527edf8d6385',
	deepbookRegistry: '0x7c256edbda983a2cd6f946655f4bf3f00a41043993781f8674a7046e8c0e11d1',
	deepbookCoreAccountPackageId:
		'0x2dbb8e6a5b9a8ac6201c7aeff6de0c7e7bca5dcd8d6c16538cb1a7447a298071',
	/** Required by every Predict session wrapper — they all take `config: &ProtocolConfig`. */
	protocolConfig: '0xfeda745dfdef2cd9721c2ff1e1de538d103bc6012469d0eec10ea5de67f636d0',
});

/**
 * Scale constants the deployment owns rather than the SDK. Deployment-wide:
 * `quoteCoinDecimals` and `fixedPointScale` apply to any subpath formatting a custody
 * balance, not just Predict.
 */
export const TESTNET_UNITS: DeploymentUnits = Object.freeze({
	positionLotSize: 10000,
	fixedPointScale: 1000000000,
	quoteCoinDecimals: 6,
	positionQuantityDecimals: 6,
});

/** Ids for DeepBook Predict — the `/predict` subpath's slice. */
export const TESTNET_PREDICT: PredictIds = Object.freeze({
	network: 'testnet',
	packages: Object.freeze({
		predict: '0x25d075d2de915feda7ab9b8f855afe59cbcd4b2ce96f75324940c810f84da018',
		account: '0x543139156cb90d1a73df33b5dca37d7c8bdce62506c7874ebc854afd319b98f1',
		propbook: '0xa04a43dbbfb123feec96691a22809d8a87e9ac37ae9356079c439750145aa92b',
	}),
	objects: Object.freeze({
		registry: '0xd21fab5444128eb65c5f6299564f583db72ad84d17581a4febe68878127100d5',
		protocolConfig: '0xfeda745dfdef2cd9721c2ff1e1de538d103bc6012469d0eec10ea5de67f636d0',
		poolVault: '0xd6b96a77d5acfd4f4a660cbd1098ed62abf2317e85a01274d1a4eeef19603767',
		oracleRegistry: '0xda71af88a8b9d01b6913937a84c5a63bb4e1015a7a2142185ec9ef73f675615f',
		accountRegistry: '0xb889caefe327cbdea58e529e3b9e10dc93f1e661ddef32824d28527edf8d6385',
	}),
	quoteCoinType: '0xc028557a1ed49e42ed091e115aedefd70a442b184c18fbec5c48d5b6c0b8c184::usdc::USDC',
	/**
	 * `plp` is the LP share coin type. It is NOT derivable from `packages.predict`: a Move
	 * type tag keeps the ORIGINAL package id across an upgrade, while `packages.predict`
	 * moves to the latest. They agree only while predict is at v1.
	 */
	coinTypes: Object.freeze({
		plp: '0x25d075d2de915feda7ab9b8f855afe59cbcd4b2ce96f75324940c810f84da018::plp::PLP',
		deep: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a8::deep::DEEP',
	}),
	units: TESTNET_UNITS,
	underlyings: Object.freeze({
		BTC: Object.freeze({
			symbol: 'BTC',
			propbookUnderlyingId: 1,
			pythFeed: '0x7179188b3a27758c53668a4ec09a81be114dea5ffabcf367f4e720a26db8ee59',
			blockScholesValueStore: '0x77dee47fb870753c740439f436e0c30c00c60f13f171c901125b3d60f89518e5',
			blockScholesSviStore: '0xe8aa80965d201e2cb18359c3aa315e3abc5bbf807a10a59d6e011ef41be5db7a',
		}),
	}),
});
