// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// GENERATED by `pnpm sync-deployment` from the deploy tooling's own manifest
// (`packages/predict/deployment/deployment.testnet.json`). Do not hand-edit:
// the next regeneration overwrites it, and a hand-patched id is exactly the drift this
// file exists to prevent. To move to a new deployment, check the sibling deepbookv3
// checkout out to the new anchor and re-run the script.
//
// Deployment: predict-testnet-8-21
// sourceCommit: 1f79fe87ab2f6b9df40cfdc2e647c93f45e6d737
//
// Runtime-dependency-free — every subpath reads a slice of this, so a value import here
// would pull that module into all of their graphs. The type import below is erased.
//
// Frozen: these are shared module singletons, so an accessor handing one to a caller who
// mutates it would change what every other caller sees.

import type {
	AccountIds,
	DeploymentInfo,
	DeploymentUnits,
	PredictIds,
	SessionsIds,
} from './types.js';

/** Which on-chain deployment the ids below came from. */
export const TESTNET_DEPLOYMENT: DeploymentInfo = Object.freeze({
	deployment: 'predict-testnet-8-21',
	network: 'testnet',
	chainId: '4c78adac',
	sourceCommit: '1f79fe87ab2f6b9df40cfdc2e647c93f45e6d737',
});

/** Ids for the shared `account` primitive — the `/account` subpath's slice. */
export const TESTNET_ACCOUNT: AccountIds = Object.freeze({
	accountPackageId: '0xa94ec89b6cbb3e2609c7ca65bd77885b7513f852922ebdf8e766851fb6f85259',
	accountRegistry: '0x5682c73d657de1546374e632369a25c82744c8a20e9b4f47e6558e3d4bde88d3',
});

/**
 * Ids for time-limited sessions — the `/sessions` subpath's slice.
 *
 * `deepbookRegistry` is only needed by the DeepBook **spot** session wrappers; the Predict
 * wrappers never take it. It is carried here so a spot caller does not have to reach into
 * the package root for one id.
 */
export const TESTNET_SESSIONS: SessionsIds = Object.freeze({
	sessionsPackageId: '0xb74170443d6d2d37cbe95c7e530dd4a1605ef714ff4f9e88e27a7ac1455451db',
	sessionsConfig: '0xdfb8e23246678649cfdd6f3f6610057d5cadd6a8911a21dbe8e34788abbfab93',
	accountPackageId: '0xa94ec89b6cbb3e2609c7ca65bd77885b7513f852922ebdf8e766851fb6f85259',
	accountRegistry: '0x5682c73d657de1546374e632369a25c82744c8a20e9b4f47e6558e3d4bde88d3',
	deepbookRegistry: '0x7c256edbda983a2cd6f946655f4bf3f00a41043993781f8674a7046e8c0e11d1',
	deepbookCoreAccountPackageId:
		'0xcc9cf1029127e7bda6da4c2ab90164d7bef751783ff13c21c2bb804cec69ebec',
	/** Required by every Predict session wrapper — they all take `config: &ProtocolConfig`. */
	protocolConfig: '0x7ef1ac99c2f0a77e7aa2602b5ea7bff68750cff0d80f09bdf827bfb345128f33',
});

/**
 * Scale constants the deployment owns rather than the SDK. Deployment-wide:
 * `quoteCoinDecimals` and `fixedPointScale` apply to any subpath formatting a custody
 * balance, not just Predict.
 */
export const TESTNET_UNITS: DeploymentUnits = Object.freeze({
	positionLotSize: 10000,
	fixedPointScale: 1000000000,
	quoteCoinDecimals: 6,
	positionQuantityDecimals: 6,
});

/** Ids for DeepBook Predict — the `/predict` subpath's slice. */
export const TESTNET_PREDICT: PredictIds = Object.freeze({
	network: 'testnet',
	packages: Object.freeze({
		predict: '0x421041754244cf0e985fb9c9f5e1f49428caf3df4cde3a7b266d8e18ea63597b',
		account: '0xa94ec89b6cbb3e2609c7ca65bd77885b7513f852922ebdf8e766851fb6f85259',
		propbook: '0xd8b402609b1728f60cf20bfaaec5255701df54350ec13e93aac39463b00bf97b',
	}),
	objects: Object.freeze({
		registry: '0x3d486bd50bb5bb5450ddbcb4f74776b6135f416c09024a6674ac266e77e1870a',
		protocolConfig: '0x7ef1ac99c2f0a77e7aa2602b5ea7bff68750cff0d80f09bdf827bfb345128f33',
		poolVault: '0x2a31f592d8fd3d0781e2233770d02d67797890ac82c3d18796d7eb0997896602',
		oracleRegistry: '0x715f5ae4aac0078f4d0c6bf9ea2815614e799e909a90b577aeb8de9ad8bab142',
		accountRegistry: '0x5682c73d657de1546374e632369a25c82744c8a20e9b4f47e6558e3d4bde88d3',
	}),
	quoteCoinType: '0xe95040085976bfd54a1a07225cd46c8a2b4e8e2b6732f140a0fc49850ba73e1a::dusdc::DUSDC',
	/**
	 * `plp` is the LP share coin type. It is NOT derivable from `packages.predict`: a Move
	 * type tag keeps the ORIGINAL package id across an upgrade, while `packages.predict`
	 * moves to the latest. They agree only while predict is at v1.
	 */
	coinTypes: Object.freeze({
		plp: '0x421041754244cf0e985fb9c9f5e1f49428caf3df4cde3a7b266d8e18ea63597b::plp::PLP',
		deep: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a8::deep::DEEP',
	}),
	units: TESTNET_UNITS,
	underlyings: Object.freeze({
		BTC: Object.freeze({
			symbol: 'BTC',
			propbookUnderlyingId: 1,
			pythFeed: '0xea8fd4624002516b28b495051c838b2c9a34a4f22ae281d328e1bec47f54cd24',
			blockScholesValueStore: '0x9b64cc860ac09e6dcd675fc579c1048792ddce51cc018f2ca16aeb4a1a5684a3',
			blockScholesSviStore: '0xd5bc586e99c8d595e0ba5e0a2ef2295e652db8934ffbeda630d60e207bedab8f',
		}),
	}),
});
