name: Trace Adapter Tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build trace-adapter
        run: pnpm --filter @mysten/trace-adapter compile

      - name: Test trace-adapter
        run: pnpm --filter @mysten/trace-adapter test
